'use client'
import Providers from "@/components/providers";
// import type { Metadata } from "next";
import "./globals.css";

import { useState } from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import Navbar from "./_components/navbar/navbar";
import { Toaster } from 'react-hot-toast';
import Footer from "./_components/footer/footer";
import  localFont  from 'next/font/local';



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


//  const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
 
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [queryClient] = useState(() => new QueryClient());

  return <>
      <html >
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <QueryClientProvider client={queryClient}>
          <Providers>
          <Navbar/>
        
         <div className="container px-10">
         {children}
         <Toaster/>
         </div>
          <Footer/>
          </Providers>
          </QueryClientProvider>
        </body>
      </html>
  </>
}
